default:
  tags:
    - saas-linux-large-amd64

stages:
    - building
    - tests
    - release

docker-build:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  interruptible: true
  stage: building

  image: docker:cli

  services:
    - docker:dind
  variables:
    DOCKER_IMAGE_NAME: "buildct-$CI_COMMIT_TAG"
  before_script:
    - apk add curl bash
    - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer" | bash
    - cp .secure_files/release-keystore.properties payload/ && cp .secure_files/release-keystore.jks payload/app/
  script:
    - docker build -t "$DOCKER_IMAGE_NAME" . --progress=plain --build-arg="APP_VERSION=$CI_COMMIT_TAG" &> docker-build.log
    - CTID=$(docker create $DOCKER_IMAGE_NAME)
    - echo $CTID
    - docker cp $CTID:/openmw-android.apk openmw-android-$CI_COMMIT_TAG.apk
    - docker rm -v $CTID

  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env

  artifacts:
    when: always
    paths:
      - ./docker-build.log
      - openmw-android-$CI_COMMIT_TAG.apk
    expire_in: never
    reports:
      dotenv: job.env

releaseJob:
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: never
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: docker-build
      artifacts: true
  script:
    - echo "Create Release $CI_COMMIT_TAG"
    - echo $JOB_ID  
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    assets:
      links:
        - name: "openmw-android-$CI_COMMIT_TAG.apk"
          url: "https://gitlab.com/cavebros/openmw-android-docker/-/jobs/$JOB_ID/artifacts/file/openmw-android-$CI_COMMIT_TAG.apk"
